---
collections:
  - name: awx.awx
    version: 21.14.0
  - name: amazon.aws
    version: 7.0.0
  - name: azure.azcollection
    version: 2.0.0
  - name: kubernetes.core
    version: 2.4.0

roles:
  - name: geerlingguy.pip
